# Generated by Django 5.2.17 on 2026-09-18 06:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_sensordata_prediction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(default='Warning', max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Acknowledged', 'Acknowledged'), ('Resolved', 'Resolved')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.machine')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.organization')),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.prediction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('Preventive', 'Preventive'), ('Corrective', 'Corrective'), ('Predictive', 'Predictive'), ('Inspection', 'Inspection')], default='Preventive', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('technician', models.CharField(blank=True, max_length=150)),
                ('cost', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('downtime_hours', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('maintenance_date', models.DateField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.machine')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.organization')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.prediction')),
            ],
            options={
                'ordering': ['-maintenance_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_machines', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_predictions', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('high_risk_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('failure_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.organization')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_threshold', models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('high_risk_threshold', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('year', models.IntegerField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.organization')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('organization', 'year')},
            },
        ),
    ]
