# Generated by Django 5.2.17 on 2026-09-18 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alert_maintenancerecord_maintenancereport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='operating_hours',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='power_consumption',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='vibration',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='air_temperature',
            field=models.FloatField(blank=True, help_text='Air temperature in Kelvin (K)', null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='process_temperature',
            field=models.FloatField(blank=True, help_text='Process temperature in Kelvin (K)', null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='tool_wear',
            field=models.FloatField(blank=True, help_text='Tool wear in minutes', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='rotational_speed',
            field=models.FloatField(blank=True, help_text='Rotational speed in RPM', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='torque',
            field=models.FloatField(blank=True, help_text='Torque in Nm', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
